import { describe, expect, it } from "vitest";
import { releaseDate, releaseNotesState } from "./repoUtils";

describe("releaseNotesState", () => {
  it("returns none for empty and whitespace-only bodies", () => {
    for (const body of [null, undefined, "", "   ", "\n\t"]) {
      expect(releaseNotesState(body)).toBe("none");
    }
  });

  it("returns generated when the body contains the annalist marker", () => {
    expect(releaseNotesState("Release notes\n<!-- generated by annalist -->")).toBe(
      "generated",
    );
    expect(releaseNotesState("  <!-- generated by annalist -->  ")).toBe(
      "generated",
    );
  });

  it("returns manual for non-empty bodies without the marker", () => {
    expect(releaseNotesState("hand-written notes")).toBe("manual");
    expect(releaseNotesState("<!-- not the annalist marker -->")).toBe("manual");
  });
});

describe("releaseDate", () => {
  it("returns a non-empty local date containing the year for a valid RFC3339 timestamp", () => {
    const label = releaseDate("2026-01-06T10:00:00Z");
    expect(label.length).toBeGreaterThan(0);
    expect(label).toContain("2026");
  });

  it("returns an empty string for missing or invalid timestamps", () => {
    expect(releaseDate(null)).toBe("");
    expect(releaseDate(undefined)).toBe("");
    expect(releaseDate("")).toBe("");
    expect(releaseDate("not-a-date")).toBe("");
  });
});
