package pipeline

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"
	"sync"

	"github.com/djdembeck/annalist/internal/config"
	"github.com/djdembeck/annalist/internal/db"
	"github.com/djdembeck/annalist/internal/engine"
	"github.com/djdembeck/annalist/internal/llm"
)

// ErrNotFound is returned by platform calls (repo file reads, release lookup)
// when the requested resource does not exist.
var ErrNotFound = errors.New("not found")

// OwnerRepo is a repository reference returned by platform listings so other
// packages can join with repo_settings without importing platform packages.
type OwnerRepo struct {
	Owner string
	Repo  string
	Fork  bool
}

// Spec identifies a single release for which to generate notes.
type Spec struct {
	Platform  string
	Owner     string
	Repo      string
	ToTag     string
	FromTag   string // optional; empty means auto-resolve the previous tag
	ReleaseID string
}

// Options controls generation behavior.
type Options struct {
	Force   bool // bypass idempotency and the don't-clobber guard
	Publish bool // write the notes into the release body
}

// Release is the small platform-agnostic view of a release.
type Release struct {
	ID   int64
	Body string
}

// RepoFileReader reads a file from a repository using platform credentials.
type RepoFileReader interface {
	ReadRepoFile(ctx context.Context, owner, repo, path string) (string, error)
}

// Platform is everything the pipeline needs from a hosting platform.
type Platform interface {
	RepoFileReader
	GetReleaseByTag(ctx context.Context, owner, repo, tag string) (*Release, error)
	EditReleaseBody(ctx context.Context, owner, repo string, releaseID int64, body string) error
	CloneInfo(ctx context.Context, owner, repo string) (cloneURL, header string, err error)
}

// Pipeline drives the whole generate flow: resolve settings, clone,
// collect the commit log, call the LLM, and optionally publish.
type Pipeline struct {
	Cfg     *config.Config
	DB      *db.Store
	LLM     *llm.Client
	Engine  *engine.Engine
	GitHub  Platform
	Forgejo Platform

	// inflight serializes generation per (platform, releaseID) so concurrent
	// webhook deliveries of the same release cannot double LLM spend or race
	// the publish (the idempotency check-then-act is atomic under the lock).
	inflight sync.Map // key: platform + "/" + releaseID -> *sync.Mutex

	// genSem bounds concurrent generations (clone + LLM + publish) so a burst
	// of signed deliveries cannot exhaust CPU, disk, or LLM budget.
	genSemOnce sync.Once
	genSem     chan struct{}
}

// sem returns the generation semaphore, initializing it lazily so tests can
// construct a Pipeline literal without going through New.
func (p *Pipeline) sem() chan struct{} {
	p.genSemOnce.Do(func() { p.genSem = make(chan struct{}, 4) })
	return p.genSem
}

// marker is written at the end of every release body this app publishes, so
// regen can identify bodies the app owns.
const marker = "<!-- generated by annalist -->"

// New builds a Pipeline. gh and fj may be nil when the platform is not
// configured; GenerateNotes reports a clear error when used anyway.
func New(cfg *config.Config, store *db.Store, llmClient *llm.Client, gh, fj Platform) *Pipeline {
	return &Pipeline{
		Cfg:     cfg,
		DB:      store,
		LLM:     llmClient,
		Engine:  &engine.Engine{LLM: llmClient},
		GitHub:  gh,
		Forgejo: fj,
	}
}

func (p *Pipeline) platformFor(platform string) (Platform, error) {
	switch platform {
	case "github":
		if p.GitHub == nil {
			return nil, errors.New("pipeline: platform github is not configured")
		}
		return p.GitHub, nil
	case "forgejo":
		if p.Forgejo == nil {
			return nil, errors.New("pipeline: platform forgejo is not configured")
		}
		return p.Forgejo, nil
	default:
		return nil, fmt.Errorf("pipeline: unknown platform %q", platform)
	}
}

// Resolve computes the effective settings for a repo. Per-repo row values
// override the global settings, which fall back to the configured LLM
// defaults. The in-repo instructions file is resolved separately inside
// GenerateNotes (highest precedence).
func (p *Pipeline) Resolve(ctx context.Context, platform, owner, repo string) (bool, engine.Resolved, error) {
	global, err := p.DB.GetSettings()
	if err != nil {
		return false, engine.Resolved{}, fmt.Errorf("pipeline: global settings: %w", err)
	}

	row, err := p.DB.GetRepoSettings(platform, owner, repo)
	if err != nil {
		return false, engine.Resolved{}, fmt.Errorf("pipeline: repo settings: %w", err)
	}

	enabled := true
	tone := global.Tone
	instructions := global.Instructions
	model := global.Model
	var temperature *float64 = global.Temperature

	if row != nil {
		enabled = row.Enabled
		if row.Tone != "" {
			tone = row.Tone
		}
		if row.Instructions != "" {
			instructions = row.Instructions
		}
		if row.Model != "" {
			model = row.Model
		}
		if row.Temperature != nil {
			temperature = row.Temperature
		}
	}

	if model == "" {
		model = p.Cfg.LLM.Model
	}
	resolved := engine.Resolved{
		Tone:         tone,
		Instructions: instructions,
		Model:        model,
		Temperature:  p.Cfg.LLM.Temperature,
	}
	if temperature != nil {
		resolved.Temperature = *temperature
	}

	return enabled, resolved, nil
}

// GenerateNotes produces release notes for spec. Notes are returned even when
// opts.Publish is false. Errors (LLM failure, clone failure, API failure)
// propagate — no fallback text — and idempotency + manual regen cover retries.
// Generation is bounded by a semaphore and serialized per (platform,
// releaseID), so concurrent webhook deliveries of the same release cannot
// double-spend the LLM or race the publish.
func (p *Pipeline) GenerateNotes(ctx context.Context, spec Spec, opts Options) (string, error) {
	select {
	case p.sem() <- struct{}{}:
		defer func() { <-p.sem() }()
	case <-ctx.Done():
		return "", ctx.Err()
	}

	mu, _ := p.inflight.LoadOrStore(spec.Platform+"/"+spec.ReleaseID, &sync.Mutex{})
	m := mu.(*sync.Mutex)
	m.Lock()
	defer m.Unlock()

	if !opts.Force {
		existing, err := p.DB.GetGenerated(spec.Platform, spec.ReleaseID)
		if err != nil {
			return "", fmt.Errorf("pipeline: check generated: %w", err)
		}
		if existing != nil {
			return existing.Notes, nil
		}
	}

	platform, err := p.platformFor(spec.Platform)
	if err != nil {
		return "", err
	}

	cloneURL, header, err := platform.CloneInfo(ctx, spec.Owner, spec.Repo)
	if err != nil {
		return "", fmt.Errorf("pipeline: clone info: %w", err)
	}

	workdir, cleanup, err := engine.CloneTo(ctx, p.Cfg.Data.Dir, spec.Platform, cloneURL, header)
	if err != nil {
		return "", fmt.Errorf("pipeline: clone: %w", err)
	}
	defer cleanup()

	from := spec.FromTag
	if from == "" {
		from = engine.ResolvePrevTag(ctx, workdir, spec.ToTag)
	}
	// Git ref names cannot start with '-' (check-ref-format); rejecting such
	// tags here prevents option-injection into the git log invocation below.
	if strings.HasPrefix(from, "-") || strings.HasPrefix(spec.ToTag, "-") {
		return "", fmt.Errorf("pipeline: invalid tag %q", spec.ToTag)
	}
	commitLog := engine.CollectCommitLog(ctx, workdir, from, spec.ToTag)

	_, resolved, err := p.Resolve(ctx, spec.Platform, spec.Owner, spec.Repo)
	if err != nil {
		return "", err
	}

	// In-repo instructions file has the highest precedence.
	instructionsPath := ".github/release-notes-instructions.md"
	if spec.Platform == "forgejo" {
		instructionsPath = ".forgejo/release-notes.md"
	}
	if content, ferr := platform.ReadRepoFile(ctx, spec.Owner, spec.Repo, instructionsPath); ferr == nil && content != "" {
		resolved.Instructions = content
	}

	var notes string
	if strings.TrimSpace(commitLog) == "" {
		notes = "No changes documented."
	} else {
		notes, err = p.Engine.Generate(ctx, resolved, spec.ToTag, from, commitLog)
		if err != nil {
			return "", err
		}
	}

	if opts.Publish {
		if err := p.Publish(ctx, spec, platform, notes, opts.Force); err != nil {
			return "", err
		}
	}

	return notes, nil
}

// Publish writes notes into the release body for spec, honoring the
// don't-clobber guard unless force is set, then records the generated note.
func (p *Pipeline) Publish(ctx context.Context, spec Spec, platform Platform, notes string, force bool) error {
	release, err := platform.GetReleaseByTag(ctx, spec.Owner, spec.Repo, spec.ToTag)
	if err != nil {
		return fmt.Errorf("pipeline: fetch release: %w", err)
	}

	if !force && release.Body != "" && !strings.Contains(release.Body, marker) {
		log.Printf("pipeline: %s/%s %s: human-edited release body; leaving it alone", spec.Owner, spec.Repo, spec.ToTag)
		return nil
	}

	body := notes
	if !strings.HasSuffix(body, marker) {
		body = body + "\n" + marker
	}
	if err := platform.EditReleaseBody(ctx, spec.Owner, spec.Repo, release.ID, body); err != nil {
		return fmt.Errorf("pipeline: edit release body: %w", err)
	}

	if err := p.DB.MarkGenerated(spec.Platform, spec.Owner, spec.Repo, spec.ReleaseID, spec.ToTag, notes); err != nil {
		return fmt.Errorf("pipeline: record generated: %w", err)
	}
	return nil
}
