// Component test for the repos page's release-listing contract: the per-repo
// Generate panel fetches its release list on open, offers tag chips that
// prefill the tag field, classifies each release's notes state, and only
// re-fetches when forced.
//
// Mirrors web/src/routes/settings/settings.test.ts: the page is mounted with
// svelte's client `mount` and queried with @testing-library/dom; the API is
// stubbed at the fetch boundary.
import { describe, it, expect, afterEach, vi } from "vitest";
import { fireEvent, screen, waitFor } from "@testing-library/dom";
import { mount, unmount, tick } from "$lib/svelte-client";

import { releaseDate } from "$lib/repoUtils";
import type { Repo, Release } from "$lib/api";
import ReposPage from "./+page.svelte";

// $app/navigation is imported (transitively, via handleAuthError's goto) only
// on the auth-error path; mock it as a resolving no-op (mirroring
// settings.test.ts) so the redirect never runs and the page's state stays
// observable.
vi.mock("$app/navigation", () => ({
  goto: vi.fn(() => Promise.resolve()),
}));

const ANNALIST_MARKER = "<!-- generated by annalist -->";

const releaseFixture: Release[] = [
  {
    id: 1,
    tag: "v1.0.0",
    body: "notes " + ANNALIST_MARKER,
    draft: false,
    created_at: "2026-01-05T10:00:00Z",
    published_at: "2026-06-15T00:00:00Z",
  },
  {
    id: 2,
    tag: "v0.9.0",
    body: "hand written notes",
    draft: false,
    created_at: "2026-02-01T00:00:00Z",
    published_at: "2026-02-02T00:00:00Z",
  },
  {
    id: 3,
    tag: "v0.8.0",
    body: "",
    draft: false,
    created_at: "2026-03-01T00:00:00Z",
    published_at: "2026-03-01T00:00:00Z",
  },
  {
    id: 4,
    tag: "v9.9.9",
    body: "",
    draft: true,
    created_at: "2026-04-01T00:00:00Z",
    published_at: null,
  },
];

const repoFixture: Repo = {
  platform: "github",
  owner: "o",
  repo: "r",
  enabled: true,
  tone: null,
  instructions: null,
  model: null,
  temperature: null,
  trigger: "auto",
  commit_types: null,
  mode: null,
  effective: {
    tone: null,
    model: null,
    temperature: null,
    instructions: null,
    source: null,
    commit_types: null,
    mode: null,
  },
};

type JsonInit = { method?: string; body?: string };

let releasesCalls = 0;
// Optional per-call override for the release-list fetch; when present it
// takes over the response (typically to hold it open or reject it).
let releasesOverride: ((n: number) => Response | Promise<Response>) | null =
  null;

function jsonResponse(data: unknown): Response {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: { "content-type": "application/json" },
  });
}

/**
 * Stub the fetch boundary. `repos` is the /api/repos payload, or an Error to
 * throw (repo-list rejection). `override` may replace the release-list
 * response per call.
 */
function mockRepos(repos: Repo[] | Error): void {
  releasesCalls = 0;
  releasesOverride = null;
  globalThis.fetch = vi.fn(async (input: string, init?: JsonInit) => {
    const url = String(input);
    if (url.endsWith("/api/repos")) {
      if (repos instanceof Error) throw repos;
      return jsonResponse(repos);
    }
    if (url.endsWith("/in-repo-instructions")) return jsonResponse({});
    if (url.endsWith("/api/models")) return jsonResponse([]);
    if (url.endsWith("/generate")) return jsonResponse({ notes: "n", published: false });
    if (url.endsWith("/releases")) {
      releasesCalls += 1;
      if (releasesOverride) return releasesOverride(releasesCalls);
      return jsonResponse(releaseFixture);
    }
    return jsonResponse([]);
  }) as unknown as typeof fetch;
}

let container: HTMLElement | null = null;
let component: ReturnType<typeof mount> | null = null;

afterEach(() => {
  if (component) {
    unmount(component);
    component = null;
  }
  container?.remove();
  container = null;
  releasesOverride = null;
  vi.clearAllMocks();
});

async function mountPage() {
  container = document.createElement("div");
  document.body.append(container);
  component = mount(ReposPage, { target: container });
  // Wait until the initial repo fetch has settled (the loading skeleton is
  // gone): either the repo card or the error banner is now present.
  await waitFor(() => {
    expect(screen.queryByText("Reading source inventory")).toBeNull();
  });
}

/** Open the Generate panel for the single repo. */
async function openGenerate() {
  await fireEvent.click(screen.getByRole("button", { name: /Generate note/ }));
  await waitFor(() => {
    expect(screen.getByRole("button", { name: /Close generation/ }));
  });
  await tick();
}

describe("repos page release listing", () => {
  it("tag-chip click prefills the tag field and clears the tag error", async () => {
    mockRepos([repoFixture]);
    await mountPage();
    await openGenerate();
    await waitFor(() => {
      expect(screen.getByRole("list", { name: /Releases for/ }));
    });

    // Trigger a tag error first: an empty tag with Preview sets the alert.
    await fireEvent.click(screen.getByRole("button", { name: /Preview/ }));
    await waitFor(() => {
      expect(screen.getByText("Enter a release tag"));
    });

    // Clicking the v1.0.0 chip prefills the tag field and clears the error.
    await fireEvent.click(screen.getByRole("button", { name: "v1.0.0" }));
    await tick();
    const input = screen.getByRole("textbox", { name: /Release tag/ });
    expect((input as HTMLInputElement).value).toBe("v1.0.0");
    expect(screen.queryByText("Enter a release tag")).toBeNull();
  });

  it("classifies each release's notes state by chip class and label", async () => {
    mockRepos([repoFixture]);
    await mountPage();
    await openGenerate();
    await waitFor(() => {
      expect(screen.getByRole("list", { name: /Releases for/ }));
    });

    // notes-by-annalist (generated marker) -> chip--annalist.
    expect(
      screen.getByText("notes by annalist").closest("span")?.className,
    ).toContain("chip--annalist");
    // hand-written body -> chip--manual.
    expect(
      screen.getByText("hand-written notes").closest("span")?.className,
    ).toContain("chip--manual");
    // empty body -> chip--none. Both no-notes releases (the two empty-body
    // rows) must carry the none class.
    const none = screen.getAllByText("no notes");
    expect(none.length).toBeGreaterThan(0);
    for (const el of none) {
      expect(el.closest("span")?.className).toContain("chip--none");
    }
  });

  it("shows a draft chip and a created_at date label when there is no published_at", async () => {
    mockRepos([repoFixture]);
    await mountPage();
    await openGenerate();
    await waitFor(() => {
      expect(screen.getByRole("list", { name: /Releases for/ }));
    });

    // The draft release shows a "draft" chip.
    expect(screen.getByText("draft"));

    // Date label is releaseDate(published_at ?? created_at). For v1.0.0 the
    // published_at (2026-06-15) wins over its created_at (2026-01-05); for the
    // draft (published_at null) the created_at (2026-04-01) is the label. The
    // test uses the page's own releaseDate helper so the comparison is exact
    // and locale-independent.
    expect(
      screen.getByText(releaseDate("2026-06-15T00:00:00Z")),
    ).toBeTruthy();
    // v1.0.0's created_at must NOT be the displayed label (published wins).
    expect(
      screen.queryByText(releaseDate("2026-01-05T00:00:00Z")),
    ).toBeNull();
    // The draft's created_at is the displayed label.
    expect(screen.getByText(releaseDate("2026-04-01T00:00:00Z"))).toBeTruthy();
  });

  it("shows the loading skeleton until the repo list resolves", async () => {
    // Hold the /api/repos fetch open, then resolve it.
    let resolveRepos: (r: Repo[]) => void = () => {};
    globalThis.fetch = vi.fn(async (input: string, init?: JsonInit) => {
      const url = String(input);
      if (url.endsWith("/api/repos")) {
        const repos = await new Promise<Repo[]>((res) => {
          resolveRepos = res;
        });
        return jsonResponse(repos);
      }
      if (url.endsWith("/in-repo-instructions")) return jsonResponse({});
      if (url.endsWith("/api/models")) return jsonResponse([]);
      if (url.endsWith("/releases")) return jsonResponse(releaseFixture);
      return jsonResponse([]);
    }) as unknown as typeof fetch;
    // Mount without waiting for settle so the loading skeleton is observable.
    container = document.createElement("div");
    document.body.append(container);
    component = mount(ReposPage, { target: container });
    await waitFor(() => {
      expect(screen.getByText("Reading source inventory"));
    });

    // While loading, the skeleton section is shown and no repo card is.
    expect(screen.queryByText("o/r")).toBeNull();

    resolveRepos([repoFixture]);
    await waitFor(() => {
      expect(screen.getByText("o/r"));
    });
  });

  it("shows a role=alert error when the repo list rejects", async () => {
    mockRepos(new Error("boom connection"));
    await mountPage();
    await waitFor(() => {
      expect(screen.getByRole("alert"));
    });
    expect(screen.getByRole("alert").textContent).toContain(
      "boom connection",
    );
    expect(screen.queryByText("o/r")).toBeNull();
  });

  it("does not re-fetch releases on reopen but the Refresh button forces it", async () => {
    mockRepos([repoFixture]);
    await mountPage();
    await openGenerate();
    await waitFor(() => {
      expect(screen.getByRole("list", { name: /Releases for/ }));
    });
    expect(releasesCalls).toBe(1);

    // Close the panel, then reopen it: the cached success must not re-fetch.
    await fireEvent.click(
      screen.getByRole("button", { name: /Close generation/ }),
    );
    await tick();
    await openGenerate();
    await waitFor(() => {
      expect(screen.getByRole("list", { name: /Releases for/ }));
    });
    expect(releasesCalls).toBe(1);

    // The Refresh button forces a re-fetch.
    await fireEvent.click(
      screen.getByRole("button", { name: /Refresh releases/ }),
    );
    await waitFor(() => {
      expect(releasesCalls).toBe(2);
    });
  });

  it("an unauthorized release fetch leaves the state untouched", async () => {
    mockRepos([repoFixture]);
    await mountPage();
    await openGenerate();
    await waitFor(() => {
      expect(screen.getByRole("list", { name: /Releases for/ }));
    });

    // Force a refresh whose fetch is rejected with 401. The page's handler
    // treats an auth error as a redirect (handleAuthError returns true) and
    // bails before setting the error state, so no "Could not load releases"
    // alert may appear even though the refresh failed.
    releasesOverride = () =>
      new Response(
        JSON.stringify({ error: "unauthorized" }),
        { status: 401, headers: { "content-type": "application/json" } },
      );
    await fireEvent.click(
      screen.getByRole("button", { name: /Refresh releases/ }),
    );
    // Let the 401 round-trip settle (releasesCalls is 1 until the forced
    // fetch has been dispatched).
    await waitFor(() => {
      expect(releasesCalls).toBe(2);
    });
    await tick();
    await tick();
    expect(
      screen.queryByRole("alert", { name: /Could not load releases/ }),
    ).toBeNull();
  });
});
